# git: show git branch in prompt
git_branch() {
    git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/(\1)/'
}

export PS1="[\u@\h \W]\$(git_branch)\$ "

# add new bin path
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi
